import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./components/providers";
const inter = Inter({ subsets: ["latin"] });
import {RecoilRoot} from "recoil";
import {AppBarClient} from "@repo/ui/AppBarClient"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppBarClient />
          {children}
        </Providers>
      </body>
    </html>
  )

}

